FROM node:11.10.1-alpine

MAINTAINER Rodrigo Cauduro

# Set environment variables
ENV APP_ROOT /app
ENV HOST 0.0.0.0
#ENV DEBUG 1

# Create app directory
RUN mkdir -p ${APP_ROOT}
COPY . ${APP_ROOT}
WORKDIR ${APP_ROOT}

RUN npm install
RUN npm run build

RUN npm rebuild node-sass


EXPOSE 3000
